name: Deploy to EKS

on:
  push:
    branches:
      - main  # ðŸš€ Dispara quando houver push na branch `master`
  workflow_dispatch:  # ðŸ”„ Permite rodar manualmente pelo GitHub Actions

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: ðŸš€ Checkout do CÃ³digo
        uses: actions/checkout@v4

      - name: ðŸ”‘ Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Mude para a regiÃ£o do seu EKS

      - name: ðŸ”„ Atualizar Kubeconfig para Acessar o EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name swile-cluster

      - name: ðŸš¢ Aplicar Deployment no Kubernetes
        run: |
          kubectl apply -f terraform/deployment.yaml
          kubectl apply -f terraform/services.yaml

      - name: âœ… Verificar os Recursos Criados
        run: |
          kubectl get pods
          kubectl get svc
